INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('ABCP11', 'Geral', 'Tijolo: Shoppings', 'Rio Bravo Investimentos', 88.49, 0.49, 0.46, 374298.07,
  0.90, 21167);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('AFCR11', 'Geral', 'Papel: CRIs', 'CM Capital Markets', 105.00, 0.80, 0.14, 29160.62,
  1.04, 109);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('BCFF11', 'Geral', 'Papel: Fundo de Fundos', 'BTG Pactual', 91.01, 0.45, 0.51, 3823169.00,
  1.09, 220471);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('BCRI11', 'Geral', 'Papel: CRIs', 'BRL Trust DTVM', 108.08, 0.73, 0.86, 771119.76,
  1.02, 29704);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('BRCR11', 'Geral', 'Tijolo: Escritórios', 'BTG Pactual', 90.54, 0.46, 0.45, 5848839.38,
  0.85, 102725);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('HABT11', 'Geral', 'Papel: CRIs', 'Vórtx DTVM LTDA', 113.50, 0.97, 0.85, 1135011.31,
  1.12, 11359);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('HCTR11', 'Geral', 'Papel: CRIs', 'Vórtx DTVM LTDA', 127.00, 2.12, 1.32, 2628091.90,
  1.09, 18057);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('HGBS11', 'Geral', 'Tijolo: Shoppings', 'Hedge Investments DTVM LTDA', 212.45, 0.25, 1.20, 3523210.17,
  0.94, 70077);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('HGLG11', 'Geral', 'Tijolo: Galpões', 'Credit Suisse Hedging-Griffo', 171.66, 0.78, 0.76, 9723814.86,
  1.27, 204757);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('HGRE11', 'Geral', 'Tijolo: Escritórios', 'Credit Suisse Hedging-Griffo', 152.59, 0.65, 0.71, 3490475.03,
  0.93, 91034);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('HGRU11', 'Geral', 'Tijolo: Educacional', 'Credit Suisse Hedging-Griffo', 132.20, 0.68, 0.68, 4949535.86,
  1.23, 61085);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('IRDM11', 'Geral', 'Papel: CRIs', 'BTG Pactual', 117.90, 1.05, 0.84, 4946926.55,
  1.21, 70837);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('KNRI11', 'Geral', 'Tijolo: Híbrido', 'INTRAG DTVM', 165.87, 0.65, 0.72, 4724009.72,
  1.06, 206394);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('MGFF11', 'Geral', 'Papel: Fundo de Fundos', 'BTG Pactual', 92.60, 0.49, 0.69, 2287886.17,
  1.09, 50018);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('MXRF11', 'Geral', 'Papel: CRIs', 'BTG Pactual', 10.55, 0.07, 0.07, 6998288.93,
  1.04, 215856);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('RBFF11', 'Geral', 'Papel: Fundo de Fundos', 'BRL Trust DTVM', 73.00, 0.55, 0.48, 607476.03,
  0.95, 8923);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('RBRF11', 'Geral', 'Papel: Fundo de Fundos', 'BTG Pactual', 95.83, 0.60, 0.67, 3246418.21,
  1.02, 51420);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('RECR11', 'Geral', 'Papel: CRIs', 'BRL Trust DTVM', 103.47, 0.90, 0.80, 1575154.55,
  1.06, 33846);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('VGIR11', 'Geral', 'Papel: CRIs', 'BTG Pactual', 83.65, 0.45, 0.65, 926251.00,
  0.86, 26638);

INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
  ('XPPR11', 'Geral', 'Papel: Fundo de Fundos', 'Vórtx DTVM LTDA', 85.99, 0.72, 0.65, 1134545.28,
  0.88, 28986);