INSERT INTO T_REAL_STATE_FUND (TICKET_NAME, TARGET_AUDIENCE, TICKET_TYPE, ADMINISTRATOR, PRICE,
  LAST_DIVIDEND_YIELD, AVERAGE_DIVIDEND_YIELD, DAILY_LIQUIDITY, PRICE_BY_EQUITY_VALUE, SHAREHOLDERS) VALUES
    ('ABCP11', 'Geral', 'Tijolo: Shoppings', 'Rio Bravo Investimentos', 88.49, 0.49, 0.46, 214526.89,
      1.04, 21158);