DROP TABLE IF EXISTS T_REAL_STATE_FUND;

CREATE TABLE T_REAL_STATE_FUND (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  TICKET_NAME VARCHAR(20) NOT NULL,
  TARGET_AUDIENCE VARCHAR(50) NOT NULL,
  TICKET_TYPE VARCHAR(100) NOT NULL,
  ADMINISTRATOR VARCHAR(200) NOT NULL,
  PRICE DECIMAL(10,2) NOT NULL,
  LAST_DIVIDEND_YIELD DECIMAL(10,2) NOT NULL,
  AVERAGE_DIVIDEND_YIELD DECIMAL(10,2) NOT NULL,
  DAILY_LIQUIDITY DECIMAL(10,2) NOT NULL,
  PRICE_BY_EQUITY_VALUE DECIMAL(10,2) NOT NULL,
  SHAREHOLDERS INT NOT NULL
);